apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        tier: backend
        app: myapp
    spec:
      containers:
      - name: backend
        image: mahrukhijaz/backend
        ports:
        - containerPort: 8080
          name: tcp
